version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
  builder: dirhtml
  fail_on_warning: true
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

