[theme]
inherit = "basic"
stylesheets = ["theme.css"]
pygments_style = { default = "bw" }
sidebars = ["sidebar_main_nav_links.html", "sidebar_toc.html"]

[options]
show_breadcrumbs = true
show_prev_next = false
show_scrolltop = false
globaltoc_includehidden = true
breadcrumbs_separator = "/"
awesome_headerlinks = true
awesome_external_links = false
main_nav_links = false
extra_header_link_icons = false
logo_dark = ""
logo_light = ""
